//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManagementSystemPresentationLayer.LicenseManagementSystemWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LicenseManagementSystemWebService.LicenseManagementSystemWebServiceSoap")]
    public interface LicenseManagementSystemWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Guid Login(string userEmail, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Guid> LoginAsync(string userEmail, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Registration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Registration(string userEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Registration", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RegistrationAsync(string userEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLicensesData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LicenseManagementSystemPresentationLayer.LicenseManagementSystemWebService.LicensesContainer GetLicensesData(string userEmail, System.Guid loggedUsersAccessNumber, int pageNumber, int columnToSort, int numberOfRowsToDisplay, bool typeOfSorting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLicensesData", ReplyAction="*")]
        System.Threading.Tasks.Task<LicenseManagementSystemPresentationLayer.LicenseManagementSystemWebService.LicensesContainer> GetLicensesDataAsync(string userEmail, System.Guid loggedUsersAccessNumber, int pageNumber, int columnToSort, int numberOfRowsToDisplay, bool typeOfSorting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogoutUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void LogoutUser(string userEmail, System.Guid loggedUsersAccessNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogoutUser", ReplyAction="*")]
        System.Threading.Tasks.Task LogoutUserAsync(string userEmail, System.Guid loggedUsersAccessNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewLicenseData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddNewLicenseData(string userEmail, System.Guid loggedUsersAccessNumber, string licenseDataUserName, string licenseDataUserEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewLicenseData", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AddNewLicenseDataAsync(string userEmail, System.Guid loggedUsersAccessNumber, string licenseDataUserName, string licenseDataUserEmail);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LicensesContainer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataSet licensesDataSetField;
        
        private int numberOfAllLicensesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Data.DataSet LicensesDataSet {
            get {
                return this.licensesDataSetField;
            }
            set {
                this.licensesDataSetField = value;
                this.RaisePropertyChanged("LicensesDataSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int NumberOfAllLicenses {
            get {
                return this.numberOfAllLicensesField;
            }
            set {
                this.numberOfAllLicensesField = value;
                this.RaisePropertyChanged("NumberOfAllLicenses");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LicenseManagementSystemWebServiceSoapChannel : LicenseManagementSystemPresentationLayer.LicenseManagementSystemWebService.LicenseManagementSystemWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LicenseManagementSystemWebServiceSoapClient : System.ServiceModel.ClientBase<LicenseManagementSystemPresentationLayer.LicenseManagementSystemWebService.LicenseManagementSystemWebServiceSoap>, LicenseManagementSystemPresentationLayer.LicenseManagementSystemWebService.LicenseManagementSystemWebServiceSoap {
        
        public LicenseManagementSystemWebServiceSoapClient() {
        }
        
        public LicenseManagementSystemWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LicenseManagementSystemWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicenseManagementSystemWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicenseManagementSystemWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid Login(string userEmail, string password) {
            return base.Channel.Login(userEmail, password);
        }
        
        public System.Threading.Tasks.Task<System.Guid> LoginAsync(string userEmail, string password) {
            return base.Channel.LoginAsync(userEmail, password);
        }
        
        public bool Registration(string userEmail, string userPassword) {
            return base.Channel.Registration(userEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrationAsync(string userEmail, string userPassword) {
            return base.Channel.RegistrationAsync(userEmail, userPassword);
        }
        
        public LicenseManagementSystemPresentationLayer.LicenseManagementSystemWebService.LicensesContainer GetLicensesData(string userEmail, System.Guid loggedUsersAccessNumber, int pageNumber, int columnToSort, int numberOfRowsToDisplay, bool typeOfSorting) {
            return base.Channel.GetLicensesData(userEmail, loggedUsersAccessNumber, pageNumber, columnToSort, numberOfRowsToDisplay, typeOfSorting);
        }
        
        public System.Threading.Tasks.Task<LicenseManagementSystemPresentationLayer.LicenseManagementSystemWebService.LicensesContainer> GetLicensesDataAsync(string userEmail, System.Guid loggedUsersAccessNumber, int pageNumber, int columnToSort, int numberOfRowsToDisplay, bool typeOfSorting) {
            return base.Channel.GetLicensesDataAsync(userEmail, loggedUsersAccessNumber, pageNumber, columnToSort, numberOfRowsToDisplay, typeOfSorting);
        }
        
        public void LogoutUser(string userEmail, System.Guid loggedUsersAccessNumber) {
            base.Channel.LogoutUser(userEmail, loggedUsersAccessNumber);
        }
        
        public System.Threading.Tasks.Task LogoutUserAsync(string userEmail, System.Guid loggedUsersAccessNumber) {
            return base.Channel.LogoutUserAsync(userEmail, loggedUsersAccessNumber);
        }
        
        public bool AddNewLicenseData(string userEmail, System.Guid loggedUsersAccessNumber, string licenseDataUserName, string licenseDataUserEmail) {
            return base.Channel.AddNewLicenseData(userEmail, loggedUsersAccessNumber, licenseDataUserName, licenseDataUserEmail);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewLicenseDataAsync(string userEmail, System.Guid loggedUsersAccessNumber, string licenseDataUserName, string licenseDataUserEmail) {
            return base.Channel.AddNewLicenseDataAsync(userEmail, loggedUsersAccessNumber, licenseDataUserName, licenseDataUserEmail);
        }
    }
}
