//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseManagementSystem.Tests.LMSWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LMSWebService.LicenseManagementSystemWebServiceSoap")]
    public interface LicenseManagementSystemWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name userEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        LicenseManagementSystem.Tests.LMSWebService.LoginResponse Login(LicenseManagementSystem.Tests.LMSWebService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<LicenseManagementSystem.Tests.LMSWebService.LoginResponse> LoginAsync(LicenseManagementSystem.Tests.LMSWebService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name userEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Registration", ReplyAction="*")]
        LicenseManagementSystem.Tests.LMSWebService.RegistrationResponse Registration(LicenseManagementSystem.Tests.LMSWebService.RegistrationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Registration", ReplyAction="*")]
        System.Threading.Tasks.Task<LicenseManagementSystem.Tests.LMSWebService.RegistrationResponse> RegistrationAsync(LicenseManagementSystem.Tests.LMSWebService.RegistrationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public LicenseManagementSystem.Tests.LMSWebService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(LicenseManagementSystem.Tests.LMSWebService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string userEmail, string password) {
            this.userEmail = userEmail;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public LicenseManagementSystem.Tests.LMSWebService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(LicenseManagementSystem.Tests.LMSWebService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Registration", Namespace="http://tempuri.org/", Order=0)]
        public LicenseManagementSystem.Tests.LMSWebService.RegistrationRequestBody Body;
        
        public RegistrationRequest() {
        }
        
        public RegistrationRequest(LicenseManagementSystem.Tests.LMSWebService.RegistrationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        public RegistrationRequestBody() {
        }
        
        public RegistrationRequestBody(string userEmail, string userPassword) {
            this.userEmail = userEmail;
            this.userPassword = userPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrationResponse", Namespace="http://tempuri.org/", Order=0)]
        public LicenseManagementSystem.Tests.LMSWebService.RegistrationResponseBody Body;
        
        public RegistrationResponse() {
        }
        
        public RegistrationResponse(LicenseManagementSystem.Tests.LMSWebService.RegistrationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegistrationResult;
        
        public RegistrationResponseBody() {
        }
        
        public RegistrationResponseBody(bool RegistrationResult) {
            this.RegistrationResult = RegistrationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LicenseManagementSystemWebServiceSoapChannel : LicenseManagementSystem.Tests.LMSWebService.LicenseManagementSystemWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LicenseManagementSystemWebServiceSoapClient : System.ServiceModel.ClientBase<LicenseManagementSystem.Tests.LMSWebService.LicenseManagementSystemWebServiceSoap>, LicenseManagementSystem.Tests.LMSWebService.LicenseManagementSystemWebServiceSoap {
        
        public LicenseManagementSystemWebServiceSoapClient() {
        }
        
        public LicenseManagementSystemWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LicenseManagementSystemWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicenseManagementSystemWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicenseManagementSystemWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LicenseManagementSystem.Tests.LMSWebService.LoginResponse LicenseManagementSystem.Tests.LMSWebService.LicenseManagementSystemWebServiceSoap.Login(LicenseManagementSystem.Tests.LMSWebService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string userEmail, string password) {
            LicenseManagementSystem.Tests.LMSWebService.LoginRequest inValue = new LicenseManagementSystem.Tests.LMSWebService.LoginRequest();
            inValue.Body = new LicenseManagementSystem.Tests.LMSWebService.LoginRequestBody();
            inValue.Body.userEmail = userEmail;
            inValue.Body.password = password;
            LicenseManagementSystem.Tests.LMSWebService.LoginResponse retVal = ((LicenseManagementSystem.Tests.LMSWebService.LicenseManagementSystemWebServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LicenseManagementSystem.Tests.LMSWebService.LoginResponse> LicenseManagementSystem.Tests.LMSWebService.LicenseManagementSystemWebServiceSoap.LoginAsync(LicenseManagementSystem.Tests.LMSWebService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<LicenseManagementSystem.Tests.LMSWebService.LoginResponse> LoginAsync(string userEmail, string password) {
            LicenseManagementSystem.Tests.LMSWebService.LoginRequest inValue = new LicenseManagementSystem.Tests.LMSWebService.LoginRequest();
            inValue.Body = new LicenseManagementSystem.Tests.LMSWebService.LoginRequestBody();
            inValue.Body.userEmail = userEmail;
            inValue.Body.password = password;
            return ((LicenseManagementSystem.Tests.LMSWebService.LicenseManagementSystemWebServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LicenseManagementSystem.Tests.LMSWebService.RegistrationResponse LicenseManagementSystem.Tests.LMSWebService.LicenseManagementSystemWebServiceSoap.Registration(LicenseManagementSystem.Tests.LMSWebService.RegistrationRequest request) {
            return base.Channel.Registration(request);
        }
        
        public bool Registration(string userEmail, string userPassword) {
            LicenseManagementSystem.Tests.LMSWebService.RegistrationRequest inValue = new LicenseManagementSystem.Tests.LMSWebService.RegistrationRequest();
            inValue.Body = new LicenseManagementSystem.Tests.LMSWebService.RegistrationRequestBody();
            inValue.Body.userEmail = userEmail;
            inValue.Body.userPassword = userPassword;
            LicenseManagementSystem.Tests.LMSWebService.RegistrationResponse retVal = ((LicenseManagementSystem.Tests.LMSWebService.LicenseManagementSystemWebServiceSoap)(this)).Registration(inValue);
            return retVal.Body.RegistrationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LicenseManagementSystem.Tests.LMSWebService.RegistrationResponse> LicenseManagementSystem.Tests.LMSWebService.LicenseManagementSystemWebServiceSoap.RegistrationAsync(LicenseManagementSystem.Tests.LMSWebService.RegistrationRequest request) {
            return base.Channel.RegistrationAsync(request);
        }
        
        public System.Threading.Tasks.Task<LicenseManagementSystem.Tests.LMSWebService.RegistrationResponse> RegistrationAsync(string userEmail, string userPassword) {
            LicenseManagementSystem.Tests.LMSWebService.RegistrationRequest inValue = new LicenseManagementSystem.Tests.LMSWebService.RegistrationRequest();
            inValue.Body = new LicenseManagementSystem.Tests.LMSWebService.RegistrationRequestBody();
            inValue.Body.userEmail = userEmail;
            inValue.Body.userPassword = userPassword;
            return ((LicenseManagementSystem.Tests.LMSWebService.LicenseManagementSystemWebServiceSoap)(this)).RegistrationAsync(inValue);
        }
    }
}
